[build]
builder = "nixpacks"
buildCommand = "pip install -r requirements/prod.txt"

[deploy]
startCommand = "python manage.py migrate --noinput && python manage.py create_admin && python manage.py collectstatic --noinput && gunicorn config.asgi:application -w 2 -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT --timeout 120"
healthcheckPath = "/health/"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
