[deploy]
startCommand = "python manage.py migrate --noinput && gunicorn config.asgi:application -w 2 -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT"
healthcheckPath = "/health/"
healthcheckTimeout = 60
